# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Estado.create(nome: 'Acre', abreviacao: 'AC')
Estado.create(nome: 'Alagoas', abreviacao: 'AL')
Estado.create(nome: 'Amapá', abreviacao: 'AP')
Estado.create(nome: 'Amazonas', abreviacao: 'AM')
Estado.create(nome: 'Bahia', abreviacao: 'BA')
Estado.create(nome: 'Ceará', abreviacao: 'CE')
Estado.create(nome: 'Distrito Federal', abreviacao: 'DF')
Estado.create(nome: 'Espírito Santo', abreviacao: 'ES')
Estado.create(nome: 'Goiás', abreviacao: 'GO')
Estado.create(nome: 'Maranhão', abreviacao: 'MA')
Estado.create(nome: 'Mato Grosso', abreviacao: 'MT')
Estado.create(nome: 'Mato Grosso do Sul', abreviacao: 'MS')
Estado.create(nome: 'Minas Gerais', abreviacao: 'MG')
Estado.create(nome: 'Pará', abreviacao: 'PA')
Estado.create(nome: 'Paraíba', abreviacao: 'PB')
Estado.create(nome: 'Paraná', abreviacao: 'PR')
Estado.create(nome: 'Pernambuco', abreviacao: 'PE')
Estado.create(nome: 'Piauí', abreviacao: 'PI')
Estado.create(nome: 'Rio de Janeiro', abreviacao: 'RJ')
Estado.create(nome: 'Rio Grande do Norte', abreviacao: 'RN')
Estado.create(nome: 'Rio Grande do Sul', abreviacao: 'RS')
Estado.create(nome: 'Rondônia', abreviacao: 'RO')
Estado.create(nome: 'Roraima', abreviacao: 'RR')
Estado.create(nome: 'Santa Catarina', abreviacao:'SC')
Estado.create(nome:'São Paulo',abreviacao:'SP')
Estado.create(nome:'Sergipe',abreviacao:'SE')
Estado.create(nome:'Tocantins',abreviacao:'TO')
